
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action SaveAction;
	private global::Gtk.Action LoadAction;
	private global::Gtk.Action CreateAction;
	private global::Gtk.Action ChangeHeightAction;
	private global::Gtk.Action CatanBaseAction;
	private global::Gtk.Action ExplorersNPirates1Action;
	private global::Gtk.Action ExplorersNPirates2Action;
	private global::Gtk.Action ExplorersNPirates3Action;
	private global::Gtk.Action ExplorersNPirates4Action;
	private global::Gtk.Action ExplorersNPirates5Action;
	private global::Gtk.Action FromFileAction;
	private global::Gtk.Action CompletelyBlankAction;
	private global::Gtk.Action BlankWaterAction;
	private global::Gtk.Action BaseAction;
	private global::Gtk.ToggleAction SeafarerSAction;
	private global::Gtk.ToggleAction ExplorersNPiratesAction;
	private global::Gtk.ToggleAction InfinityAction;
	private global::Gtk.ToggleAction fiveAction;
	private global::Gtk.ToggleAction sixAction;
	private global::Gtk.ToggleAction sevenAction;
	private global::Gtk.ToggleAction eightAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar3;
	private global::Gtk.Image image1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.LoadAction = new global::Gtk.Action ("LoadAction", global::Mono.Unix.Catalog.GetString ("Load"), null, null);
		this.LoadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load");
		w1.Add (this.LoadAction, null);
		this.CreateAction = new global::Gtk.Action ("CreateAction", global::Mono.Unix.Catalog.GetString ("Create"), null, null);
		this.CreateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create");
		w1.Add (this.CreateAction, null);
		this.ChangeHeightAction = new global::Gtk.Action ("ChangeHeightAction", global::Mono.Unix.Catalog.GetString ("Change Height"), null, null);
		this.ChangeHeightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Change Height");
		w1.Add (this.ChangeHeightAction, null);
		this.CatanBaseAction = new global::Gtk.Action ("CatanBaseAction", global::Mono.Unix.Catalog.GetString ("Catan Base"), null, null);
		this.CatanBaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Catan Base");
		w1.Add (this.CatanBaseAction, null);
		this.ExplorersNPirates1Action = new global::Gtk.Action ("ExplorersNPirates1Action", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 1"), null, null);
		this.ExplorersNPirates1Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 1");
		w1.Add (this.ExplorersNPirates1Action, null);
		this.ExplorersNPirates2Action = new global::Gtk.Action ("ExplorersNPirates2Action", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 2"), null, null);
		this.ExplorersNPirates2Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 2");
		w1.Add (this.ExplorersNPirates2Action, null);
		this.ExplorersNPirates3Action = new global::Gtk.Action ("ExplorersNPirates3Action", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 3"), null, null);
		this.ExplorersNPirates3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 3");
		w1.Add (this.ExplorersNPirates3Action, null);
		this.ExplorersNPirates4Action = new global::Gtk.Action ("ExplorersNPirates4Action", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 4"), null, null);
		this.ExplorersNPirates4Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 4");
		w1.Add (this.ExplorersNPirates4Action, null);
		this.ExplorersNPirates5Action = new global::Gtk.Action ("ExplorersNPirates5Action", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 5"), null, null);
		this.ExplorersNPirates5Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates 5");
		w1.Add (this.ExplorersNPirates5Action, null);
		this.FromFileAction = new global::Gtk.Action ("FromFileAction", global::Mono.Unix.Catalog.GetString ("From File"), null, null);
		this.FromFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("From File");
		w1.Add (this.FromFileAction, null);
		this.CompletelyBlankAction = new global::Gtk.Action ("CompletelyBlankAction", global::Mono.Unix.Catalog.GetString ("Completely Blank"), null, null);
		this.CompletelyBlankAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Completely Blank");
		w1.Add (this.CompletelyBlankAction, null);
		this.BlankWaterAction = new global::Gtk.Action ("BlankWaterAction", global::Mono.Unix.Catalog.GetString ("Blank Water"), null, null);
		this.BlankWaterAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Blank Water");
		w1.Add (this.BlankWaterAction, null);
		this.BaseAction = new global::Gtk.Action ("BaseAction", global::Mono.Unix.Catalog.GetString ("*Base*"), null, null);
		this.BaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("*Base*");
		w1.Add (this.BaseAction, null);
		this.SeafarerSAction = new global::Gtk.ToggleAction ("SeafarerSAction", global::Mono.Unix.Catalog.GetString ("Seafarer\'s"), null, null);
		this.SeafarerSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Seafarer\'s");
		w1.Add (this.SeafarerSAction, null);
		this.ExplorersNPiratesAction = new global::Gtk.ToggleAction ("ExplorersNPiratesAction", global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates"), null, null);
		this.ExplorersNPiratesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Explorers \'n Pirates");
		w1.Add (this.ExplorersNPiratesAction, null);
		this.InfinityAction = new global::Gtk.ToggleAction ("InfinityAction", global::Mono.Unix.Catalog.GetString ("Infinity"), null, null);
		this.InfinityAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Infinity");
		w1.Add (this.InfinityAction, null);
		this.fiveAction = new global::Gtk.ToggleAction ("fiveAction", global::Mono.Unix.Catalog.GetString ("five"), null, null);
		this.fiveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("5");
		w1.Add (this.fiveAction, null);
		this.sixAction = new global::Gtk.ToggleAction ("sixAction", global::Mono.Unix.Catalog.GetString ("six"), null, null);
		this.sixAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("6");
		w1.Add (this.sixAction, null);
		this.sevenAction = new global::Gtk.ToggleAction ("sevenAction", global::Mono.Unix.Catalog.GetString ("seven"), null, null);
		this.sevenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("7");
		w1.Add (this.sevenAction, null);
		this.eightAction = new global::Gtk.ToggleAction ("eightAction", global::Mono.Unix.Catalog.GetString ("eight"), null, null);
		this.eightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("8");
		w1.Add (this.eightAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Settlers of Catan");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.DefaultWidth = 804;
		this.DefaultHeight = 486;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar3'><menu name='SaveAction' action='SaveAction'/><menu name='LoadAction' action='LoadAction'><menuitem name='CatanBaseAction' action='CatanBaseAction'/><menuitem name='ExplorersNPirates1Action' action='ExplorersNPirates1Action'/><menuitem name='ExplorersNPirates2Action' action='ExplorersNPirates2Action'/><menuitem name='ExplorersNPirates3Action' action='ExplorersNPirates3Action'/><menuitem name='ExplorersNPirates4Action' action='ExplorersNPirates4Action'/><menuitem name='ExplorersNPirates5Action' action='ExplorersNPirates5Action'/><menuitem name='FromFileAction' action='FromFileAction'/><menuitem name='CompletelyBlankAction' action='CompletelyBlankAction'/><menuitem name='BlankWaterAction' action='BlankWaterAction'/></menu><menu name='CreateAction' action='CreateAction'><menuitem name='BaseAction' action='BaseAction'/><menuitem name='SeafarerSAction' action='SeafarerSAction'/><menuitem name='ExplorersNPiratesAction' action='ExplorersNPiratesAction'/><menuitem name='InfinityAction' action='InfinityAction'/></menu><menu name='ChangeHeightAction' action='ChangeHeightAction'><menuitem name='fiveAction' action='fiveAction'/><menuitem name='sixAction' action='sixAction'/><menuitem name='sevenAction' action='sevenAction'/><menuitem name='eightAction' action='eightAction'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox1.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image ();
		this.image1.Name = "image1";
		this.vbox1.Add (this.image1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
